name = input('Enter the names of the patient: ')
print(name)
Age = input('Enter the age of the patient: ')
print(Age + ' Years')
Residence = input('Enter the village name of the patient: ')
print('location: ' + Residence)
Medicine_1 = input('Enter the name of the first medicine: ')
Price_1 = input('Cost of first medicine: ')
First = str(Medicine_1 + Price_1)
print(First)